#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

set -xe

DRUPAL_SITE_DIR=${OPENSHIFT_REPO_DIR}php/sites

#
# Automatic installation only works with mysql.
# 
if [ -z "$OPENSHIFT_MYSQL_DB_HOST" ]
then
    echo 1>&2
    echo "Could not find mysql database. Please run:" 1>&2
    echo "rhc cartridge add mysql -a $OPENSHIFT_APP_NAME" 1>&2
    echo "then make a sample commit (add whitespace somewhere) and re-push" 1>&2
    echo 1>&2
fi

if [ -z "$OPENSHIFT_MYSQL_DB_HOST" ]
then
    exit 5
fi
if [ -z "$OPENSHIFT_MYSQL_DB_PORT" ]
then
    exit 6
fi

# We always have a settings.php, so instead check for a system table to see if
# Drupal is installed.
if [ ! `drush sqlq "SHOW TABLES LIKE '%system'" | grep -q system` ]
then
  if ! drush site-install standard --site-name=${OPENSHIFT_APP_NAME} --sites-subdir=default --account-pass=openshift_changeme --yes
  then
    echo "Unable to configure your Drupal installation"
    echo
    exit 10
  fi
fi

echo
echo "Drupal is now configured"
echo
echo "===================================================="
echo "  Drupal-Admin login: admin"
echo "  Drupal-Admin password: openshift_changeme"
echo "  Don't forget to change your drupal admin password!"
echo "===================================================="
