#!/bin/bash

# Try making the sites dir writeable for git's benefit.
DRUPAL_SITES_DIR="${OPENSHIFT_REPO_DIR}php/sites"
for site in `find ${OPENSHIFT_REPO_DIR}php/sites -maxdepth 1 -mindepth 1 -type d -not -iname all`; do
  chmod ugo-wX $site
  chmod ugo-wX $site/settings.php
done
